apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  DB_TYPE: "postgresdb"
  N8N_HOST: "n8n.vortechron.com"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "https"
  WEBHOOK_URL: "https://n8n.vortechron.com/"
  GENERIC_TIMEZONE: "Asia/Singapore"
  N8N_METRICS: "true"