apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: n8n
type: Opaque
data:
  # postgres
  POSTGRES_USER: cG9zdGdyZXM=
  # n8ndb
  POSTGRES_DB: bjhuZGI=
  # your-secure-password-here
  POSTGRES_PASSWORD: eW91ci1zZWN1cmUtcGFzc3dvcmQtaGVyZQ==